// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    id, 
    email, 
    password, 
    first_name, 
    last_name
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, email, first_name, last_name, status, created_at
`

type CreateUserParams struct {
	ID        pgtype.UUID
	Email     string
	Password  string
	FirstName string
	LastName  string
}

type CreateUserRow struct {
	ID        pgtype.UUID
	Email     string
	FirstName string
	LastName  string
	Status    UserStatus
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (*CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.Password,
		arg.FirstName,
		arg.LastName,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.Status,
		&i.CreatedAt,
	)
	return &i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT 
    u.id, 
    u.email, 
    u.password, 
    u.first_name, 
    u.last_name, 
    u.status, 
    u.created_at,
    r.name AS role_name
FROM users u
INNER JOIN user_roles ur ON u.id = ur.user_id
INNER JOIN roles r ON ur.role_id = r.id
WHERE u.email = $1
LIMIT 1
`

type GetUserByEmailRow struct {
	ID        pgtype.UUID
	Email     string
	Password  string
	FirstName string
	LastName  string
	Status    UserStatus
	CreatedAt pgtype.Timestamptz
	RoleName  string
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (*GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.FirstName,
		&i.LastName,
		&i.Status,
		&i.CreatedAt,
		&i.RoleName,
	)
	return &i, err
}
