// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    email,
    password,
    full_name,
    role,
    status
)
VALUES ($1, $2, $3, $4, COALESCE($5, 'active'))
RETURNING
    id,
    email,
    password,
    full_name,
    role,
    status
`

type CreateUserParams struct {
	Email    string
	Password string
	FullName string
	Role     UserRole
	Column5  interface{}
}

type CreateUserRow struct {
	ID       int32
	Email    string
	Password string
	FullName string
	Role     UserRole
	Status   NullUserStatus
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.Password,
		arg.FullName,
		arg.Role,
		arg.Column5,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.FullName,
		&i.Role,
		&i.Status,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getAll = `-- name: GetAll :many
SELECT
    id,
    email,
    password,
    full_name,
    role,
    status
FROM users
ORDER BY full_name ASC
LIMIT $1 OFFSET $2
`

type GetAllParams struct {
	Limit  int32
	Offset int32
}

type GetAllRow struct {
	ID       int32
	Email    string
	Password string
	FullName string
	Role     UserRole
	Status   NullUserStatus
}

func (q *Queries) GetAll(ctx context.Context, arg GetAllParams) ([]GetAllRow, error) {
	rows, err := q.db.Query(ctx, getAll, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllRow
	for rows.Next() {
		var i GetAllRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Password,
			&i.FullName,
			&i.Role,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT
    id,
    email,
    password,
    full_name,
    role,
    status
FROM users
WHERE email = $1
LIMIT 1
`

type GetUserByEmailRow struct {
	ID       int32
	Email    string
	Password string
	FullName string
	Role     UserRole
	Status   NullUserStatus
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.FullName,
		&i.Role,
		&i.Status,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT
    id,
    email,
    password,
    full_name,
    role,
    status
FROM users
WHERE id = $1
LIMIT 1
`

type GetUserByIDRow struct {
	ID       int32
	Email    string
	Password string
	FullName string
	Role     UserRole
	Status   NullUserStatus
}

func (q *Queries) GetUserByID(ctx context.Context, id int32) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.FullName,
		&i.Role,
		&i.Status,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users
SET
    email = $2,
    full_name = $3,
    role = $4,
    status = $5
WHERE id = $1
`

type UpdateUserParams struct {
	ID       int32
	Email    string
	FullName string
	Role     UserRole
	Status   NullUserStatus
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.Exec(ctx, updateUser,
		arg.ID,
		arg.Email,
		arg.FullName,
		arg.Role,
		arg.Status,
	)
	return err
}
