// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type TagSentiment string

const (
	TagSentimentPositive TagSentiment = "positive"
	TagSentimentNeutral  TagSentiment = "neutral"
	TagSentimentNegative TagSentiment = "negative"
)

func (e *TagSentiment) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TagSentiment(s)
	case string:
		*e = TagSentiment(s)
	default:
		return fmt.Errorf("unsupported scan type for TagSentiment: %T", src)
	}
	return nil
}

type NullTagSentiment struct {
	TagSentiment TagSentiment
	Valid        bool // Valid is true if TagSentiment is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTagSentiment) Scan(value interface{}) error {
	if value == nil {
		ns.TagSentiment, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TagSentiment.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTagSentiment) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TagSentiment), nil
}

type UserStatus string

const (
	UserStatusActive   UserStatus = "active"
	UserStatusInactive UserStatus = "inactive"
	UserStatusBlocked  UserStatus = "blocked"
)

func (e *UserStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserStatus(s)
	case string:
		*e = UserStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for UserStatus: %T", src)
	}
	return nil
}

type NullUserStatus struct {
	UserStatus UserStatus
	Valid      bool // Valid is true if UserStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserStatus) Scan(value interface{}) error {
	if value == nil {
		ns.UserStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserStatus), nil
}

type Department struct {
	ID          int32
	Name        string
	Description pgtype.Text
	CreatedAt   pgtype.Timestamptz
}

type Favorite struct {
	UserID    pgtype.UUID
	TeacherID pgtype.UUID
	CreatedAt pgtype.Timestamptz
}

type PasswordReset struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Code      string
	Used      bool
	ExpiresAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type Review struct {
	ID        pgtype.UUID
	StudentID pgtype.UUID
	TeacherID pgtype.UUID
	Content   string
	Rating    int16
	Likes     int32
	Dislikes  int32
	CreatedAt pgtype.Timestamptz
}

type ReviewTag struct {
	ReviewID  pgtype.UUID
	TagID     int32
	TeacherID pgtype.UUID
}

type Role struct {
	ID   int16
	Name string
}

type Tag struct {
	ID        int32
	Name      string
	Sentiment TagSentiment
}

type Teacher struct {
	ID            pgtype.UUID
	DepartmentID  int32
	Profession    pgtype.Text
	Description   pgtype.Text
	Experience    pgtype.Text
	AverageRating pgtype.Numeric
	TotalReviews  int32
	IsFeatured    bool
	CreatedAt     pgtype.Timestamptz
}

type TeacherCourse struct {
	ID         int32
	TeacherID  pgtype.UUID
	CourseName string
	CreatedAt  pgtype.Timestamptz
}

type TeacherUniversity struct {
	ID             int32
	TeacherID      pgtype.UUID
	UniversityName string
}

type User struct {
	ID        pgtype.UUID
	Email     string
	Password  string
	FirstName string
	LastName  string
	Status    UserStatus
	CreatedAt pgtype.Timestamptz
}

type UserRole struct {
	UserID pgtype.UUID
	RoleID int16
}
